import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import './App.css'

const notoSansJP400 = Noto_Sans_JP({
    weight: '400',
    display: 'swap',
    preload: false,
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function App() {

  return (
      <div>
        <h1>Hello</h1>
      </div>
  )
}

export default App
